### PR TITLE
Added clearer description for --o option

### PR DESCRIPTION
**Pull request by meandavejustice**
Took me a second to understand what was going on after first running `--help`. Hopefully this is a bit more clear.

love this tool by the way!

### CODE REVIEW

**Comment by holman** [comment]
Hm. I can't actually remember at the moment- does it want a directory there, or the full path to the .gif?

Thanks for this, by the way!

**Comment by meandavejustice** [comment]
It wants the full path to the gif, no problem :)

**Comment by meandavejustice** [comment]
[Here](https://github.com/holman/gifme/blob/master/bin/gifme#L10) output is set to the .gif path.

Then [here](https://github.com/holman/gifme/blob/master/bin/gifme#L34) the -o option is parsed to replace it. `animated-#{timestamp}.gif` is not appended anywhere after this.

**Comment by holman** [comment]
:cool:

**Pull request merged**
