### PR TITLE
Add support for using photos from the iSight camera

### PR DESCRIPTION
**Pull request by aw**
Yeah baby!

### CODE REVIEW

**Comment by holman** [comment]
U R :COOL:

I love it, especially since @maddox's thing depends on some shit that doesn't exist anymore, iirc. I'll check this and add it soon (and then maybe rewrite the project since it's getting a bit large).

**Comment by aw** [comment]
Awesome!
:+1:

**Comment by bhardin** [comment]
Why did this functionality get pulled from version 0.0.8? I thought it was cool.

**Comment by holman** [comment]
I like simple, focused things. This added a lot of code (and dependencies).

**Pull request merged**
